### ISSUE TITLE
Python input file writing

### ISSUE THREAD

**Issue by msanchezmartinez** [ulgltas/VLM#1]
The input file format is somewhat terse. This is especially true of the more complex files detailing the geometry, such as [this wing](https://github.com/ulgltas/VLM/blob/master/tests/Bird_Wing/Wing-4Sct.arp).

The objective is adding a user-friendly Python layer that can help when employing the code for new applications, building new test cases and coupling to CUPyDO. The reasoning behind using Python is its relative ease of use, as well as it being cross-platform. Currently, the code works at least on OS X (with `clang`), Debian & Ubuntu (with `gcc`), and Windows (with MSVC). It would be very good to keep it this way.

The format is not that complicated. I have already an almost-complete description of the meaning of the different lines as parsed by the code. This description is on paper, though it can be derived from the code.

**Comment by acrovato** [comment]
I think you can close this ;)

**Comment by msanchezmartinez** [comment]
As of #4 and #6 this is done.
