### ISSUE TITLE
Python wrapper and testing

### ISSUE THREAD

**Issue by msanchezmartinez** [ulgltas/VLM#2]
Adding a Python wrapper over the C code would help with usability as well. Furthermore, it would be useful to have a structure similar to the one in [CUPyDO](https://github.com/ulgltas/CUPyDO). In that way, the results of different tests will be automatically compared to avoid introducing any different behaviour.

This could be done using, for example, SWIG. Another advantage of the wrapper is being able to call it directly from a (future) CUPyDO interface.

**Comment by acrovato** [comment]
I think you can close this ;)

**Comment by msanchezmartinez** [comment]
As of #4 and #6 this is done.
